package pe.gob.osinergmin.pgim.utils;

public class ConstRelacionPasoFiscalizacion {

    public static final Long F1_APROBARREVANTECEDENTES_F1_APRBRINSTRMNTOSMDCION = 855L;

    public static final Long F1_APROBARREVANTECEDENTES_F1_PREPARARINICIOFISCACAMPO = 784L;    

    public static final Long F1_PREPARARINICIOFISCACAMPO_F2_INICIARFISCALIZACIONCAMPO = 785L;    

    public static final Long F2_INICIARFISCALIZACIONCAMPO_F2_REALIZARMEDICIONESYVERIFICARHECHOS = 978L;
    
    public static final Long F3_ELABORARYPRESENTARINFDESUPE_F4_REVISARYAPROBARINFSUPE = 26L;    

    public static final Long F4_VERIFVALNOTIFFISICOCAF_F5_CONFIRMAHCONSTATAEINFRAC = 737L;

    public static final Long F4_VERIFVALNOTIFELECOCAF_F5_CONFIRMAHCONSTATAEINFRAC = 741L;

    public static final Long F4_REVISARYAPROBARINFSUPE_F3_ELABORARYPRESENTARINFDESUPE = 37L;

    public static final Long F4_REVISARYAPROBARINFSUPE_F3_ELBRARINFCRCTRSTCASYCNDCIONESOFRCDAS = 980L;
    
    public static final Long F2_INICIARFISCALIZACIONCAMPO_F1_PREPARARINICIOFISCACAMPO = 1012L;   
    
}
